server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 개발 단계에서는 update, 운영은 validate 또는 none 추천
    show-sql: true       # 실행되는 SQL 출력
    properties:
      hibernate:
        format_sql: true # SQL 보기 좋게 줄바꿈
        dialect: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: always

  jackson:
    serialization:
      fail-on-empty-beans: false  # (LAZY 객체 JSON 직렬화 오류 방지용)

cors:
  allowed-origins:
    - http://localhost:3000
    - https://localhost:3000
    - ${FRONT_URL}

logging:
  level:
    root: INFO
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql: OFF
    org.springframework: WARN
    com.minjaedev.blogback: DEBUG

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 3600000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs